// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/TankDriveCommand.h"
#include "Commands/TeleopDriveStraight.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// Jacob added a comment here!!
// Comment from Linux PC

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystickRight.reset(new frc::Joystick(1));
    joystickLeft.reset(new frc::Joystick(0));
    
    // Create button for straight drive in TeleOp
    thumbLeft.reset(new frc::JoystickButton(joystickLeft.get(), 1));

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Tank Drive Command", new TankDriveCommand());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystickLeft() {
   return joystickLeft;
}

std::shared_ptr<frc::Joystick> OI::getJoystickRight() {
   return joystickRight;
}

std::shared_ptr<frc::JoystickButton> OI::getThumbLeft() {
   return thumbLeft;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
