// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef VISIONDRIVE_H
#define VISIONDRIVE_H


#include "frc/commands/Subsystem.h"
#include "Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class VisionDrive: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	VisionDrive();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

	nt::NetworkTableEntry getXEntry();
	nt::NetworkTableEntry getYEntry();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	const double vmax = 560.0; //in RPM
	const double dT = 0.002;
	double initialPosition = 0;		//motion profile vals to be edited later. 
	const double robotRadius = 31.0;
	const double wheelRadius = 2.0;

	nt::NetworkTableEntry xEntry;
	nt::NetworkTableEntry yEntry;
};

#endif
