// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/TankDriveCommand.h"
#include "Commands/TeleopDriveStraight.h"
#include <iostream>

double left;
double right; //create the variables here so they can be used in all methods of this class. 

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TankDriveCommand::TankDriveCommand(): frc::Command() {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TankDriveCommand::Initialize() {
    left = Robot::oi->getJoystickLeft()->GetY(frc::GenericHID::JoystickHand::kLeftHand);
    right = Robot::oi->getJoystickRight()->GetY(frc::GenericHID::JoystickHand::kRightHand);
    //acquire first value. 

    if( (left > 0.0) || (right > 0.0) || (left < 0.0) || (right < 0.0)){
        left = 0.0;
        right = 0.0;

        // If any of the axis values are not zeroes in, then when TankDrive initalises
        // it will fix this using the decision making. 
        //ONLY FOR Y AXIS
    }
}

// Called repeatedly when this Command is scheduled to run
void TankDriveCommand::Execute() {
    // Get joystick values from OI class periodically. 
    left = Robot::oi->getJoystickLeft()->GetY(frc::GenericHID::JoystickHand::kLeftHand);
    right = Robot::oi->getJoystickRight()->GetY(frc::GenericHID::JoystickHand::kRightHand);
    
    //std::cout << "Left: " << left << std::endl;
    //std::cout << "Right: " << right << std::endl;

    //Robot::driveTrain->TankDrive(left, right);
    Robot::driveTrain->ArcadeDrive();

    Robot::oi->getThumbLeft()->WhileHeld(new TeleopDriveStraight());
    //Robot::oi->getThumbLeft->ToggleWhenPressed(new TeleopDriveStraight());
}

// Make this return true when this Command no longer needs to run execute()
bool TankDriveCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void TankDriveCommand::End() {
    
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TankDriveCommand::Interrupted() {

}
